---
title: "Presentations - Satoshi Kume, Ph.D"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
      toc_float: false
editor_options: 
  chunk_output_type: console
---

# Invited talks

1. Satoshi Kume: The 12th JSFS Annual Meeting, Japanese Society of Fatigue Science (Yokohama, May 2016)

2. Satoshi Kume: The 108th Annual Meeting of the Japanese Society of Pathology (Tokyo, May 2019)

3. Satoshi Kume: The 75th Microscopy Annual Meeting, the Japanese Society of Microscopy (Nagoya, June 2019)

4. Satoshi Kume: The 51st Annual Meeting of the Japanese Society for Clinical Molecular Morphology (Kurume, Sep 2019)

5.	Satoshi Kume: RIKEN-CAS Young Researcher Exchange Meeting (Chinese Academy of Science, Shenzhen, China), Nov 2019.

6.	Satoshi Kume: A3 Foresight Program Meeting 2019 (Seoul National University Hospital, Seoul, Korea), Oct  2019.

7. Satoshi Kume: Introduction to Bioimaging Analysis in R, [Bioc Asia 2021 workshop](https://biocasia2021.bioconductor.org/workshops/), Online Nov 2021.

# Presentations 

1. 久米 慧嗣, 古崎 晃司: [高分子材料オントロジーの構築に向けたWikidataからのドメイン概念抽出](https://www.jstage.jst.go.jp/article/jsaisigtwo/2020/SWO-052/2020_03/_article/-char/ja/), 人工知能学会第二種研究会資料, 2020 巻 SWO-052 号 p. 03. (2020年11月)


